##############################################################################################
# Copyright 2014-2015 Cloud Media Sdn. Bhd.
#
# This file is part of Xuan Application Development SDK.
#
# Xuan Application Development SDK is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Xuan Application Development SDK is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Xuan Application Development SDK.  If not, see <http://www.gnu.org/licenses/>.
##############################################################################################

class Event(object):
    '''
    Store any event relate information
    '''

    '''
    Event Tag
    '''

    '''
    Logger Event
    '''
    EVENT_LOGGER_STATUS_CHANGED = "LOGGER_STATUS_CHANGED"

    '''
    Application Manager
    '''

    EVENT_APP_LAUNCH_STARTING = "APP_LAUNCH_STARTING"
    EVENT_APP_LAUNCH_COMPLETE = "APP_LAUNCH_COMPLETE"
    EVENT_APP_EXIT = "APP_EXIT"
    EVENT_APP_INSTALL_COMPLETED = "APP_INSTALL_COMPLETED"
    EVENT_APP_UNINSTALL_COMPLETED = "APP_UNINSTALL_COMPLETED"
    EVENT_SYSTEM_PROCESS_TERMINATE = "SYSTEM_PROCESS_TERMINATE"

    '''
    Driver Manager
    '''
    EVENT_DRIVER_UP = "DRIVER_UP"
    EVENT_DRIVER_DOWN = "DRIVER_DOWN"

    '''
    Device Manager
    '''
    EVENT_DEVICE_MANAGER_PROTOCOL_ENABLED = "DEVICE_MANAGER_PROTOCOL_ENABLED"
    EVENT_DEVICE_MANAGER_PROTOCOL_DISABLED = "DEVICE_MANAGER_PROTOCOL_DISABLED"
    
    EVENT_UPDATE_PAIRED_DEVICE_START = "UPDATE_PAIRED_DEVICE_START"
    EVENT_PAIRED_DEVICE_ENABLED = "PAIRED_DEVICE_ENABLED"
    EVENT_PAIRED_DEVICE_DISABLED = "PAIRED_DEVICE_DISABLED"
    EVENT_UPDATE_PAIRED_DEVICE_END = "UPDATE_PAIRED_DEVICE_DONE"
    EVENT_PAIRED_DEVICE_INFO_UPDATED = "EVENT_PAIRED_DEVICE_INFO_UPDATED"

    EVENT_SCAN_DEVICE_DONE = "SCAN_DEVICE_DONE"
    EVENT_SCAN_DEVICE_TIMEOUT = "SCAN_DEVICE_TIMEOUT"
    EVENT_SCAN_DEVICE_FAIL = "SCAN_DEVICE_FAIL"
    EVENT_SCAN_DEVICE_STOP = "SCAN_DEVICE_STOP"
    
    EVENT_SCAN_DEVICE_ZWAVE_USER_ACTION_REQUIRED = "SCAN_DEVICE_ZWAVE_USER_ACTION_REQUIRED"
    EVENT_SCAN_DEVICE_ZWAVE_USER_ACTION_DETECTED = "SCAN_DEVICE_ZWAVE_USER_ACTION_DETECTED"
    EVENT_SCAN_DEVICE_ZWAVE_FOUND = "SCAN_DEVICE_ZWAVE_FOUND"
    
    EVENT_PAIR_DEVICE = "PAIR_DEVICE"
    EVENT_PAIR_DEVICE_ERROR_EXIST = "PAIR_DEVICE_ERROR_EXIST"
    EVENT_PAIR_DEVICE_ERROR_UNKNOWN = "PAIR_DEVICE_ERROR_UNKNOWN"
    
    EVENT_SCAN_DEVICE_WEMO_FOUND = "SCAN_DEVICE_WEMO_FOUND"
    
    
    
    EVENT_SCAN_DEVICE_GOOGLE_NEST_USER_INPUT_REQUIRED = "SCAN_DEVICE_GOOGLE_NEST_USER_INPUT_REQUIRED"
    EVENT_SCAN_DEVICE_GOOGLE_NEST_FOUND = "SCAN_DEVICE_GOOGLE_NEST_FOUND"
    
    EVENT_SCAN_DEVICE_USER_ACTION_TIMEOUT = "SCAN_DEVICE_USER_ACTION_TIMEOUT"
    EVENT_SCAN_DEVICE_ERROR_EXIST = "SCAN_DEVICE_ERROR_EXIST"
    EVENT_SCAN_DEVICE_ERROR_UNKNOWN = "SCAN_DEVICE_ERROR_UNKNOWN"
    
    EVENT_SCAN_DEVICE_X10_USER_ACTION_REQUIRED = "SCAN_DEVICE_X10_USER_ACTION_REQUIRED"
    EVENT_SCAN_DEVICE_X10_USER_ACTION_DETECTED = "SCAN_DEVICE_X10_USER_ACTION_DETECTED"
    EVENT_SCAN_DEVICE_X10_USER_INPUT_REQUIRED = "SCAN_DEVICE_X10_USER_INPUT_REQUIRED"
    EVENT_SCAN_DEVICE_X10_DEVICE_SETUP_REQUIRED = "SCAN_DEVICE_X10_DEVICE_SETUP_REQUIRED"

    EVENT_SCAN_DEVICE_WIFI_PHILIPHUE_USER_ACTION_REQUIRED = "SCAN_DEVICE_WIFI_PHILIPHUE_USER_ACTION_REQUIRED"
    EVENT_SCAN_DEVICE_WIFI_PHILIPHUE_USER_ACTION_DETECTED = "SCAN_DEVICE_WIFI_PHILIPHUE_USER_ACTION_DETECTED"
    
    EVENT_SCAN_DEVICE_INSTEON_USER_ACTION_REQUIRED = "SCAN_DEVICE_INSTEON_USER_ACTION_REQUIRED"
    EVENT_SCAN_DEVICE_INSTEON_HUB_AUTHENTICATION_REQUIRED = "SCAN_DEVICE_INSTEON_HUB_AUTHENTICATION_REQUIRED"
    EVENT_SCAN_DEVICE_INSTEON_HUB_AUTHENTICATION_TIMEOUT = "SCAN_DEVICE_INSTEON_HUB_AUTHENTICATION_TIMEOUT"
    
    EVENT_SCAN_DEVICE_UPNP_FOUND = "SCAN_DEVICE_UPNP_FOUND"
    EVENT_SCAN_DEVICE_BLUETOOTH_FOUND = "SCAN_DEVICE_BLUETOOTH_FOUND"
    
    EVENT_SCAN_DEVICE_WIFI_PHILIP_HUE_FOUND = "SCAN_DEVICE_WIFI_PHILIP_HUE_FOUND"
    EVENT_SCAN_DEVICE_FOSCAM_HD_FOUND = "SCAN_DEVICE_FOSCAM_HD_FOUND"
    EVENT_SCAN_DEVICE_X10_RECEIVER_FOUND = "SCAN_DEVICE_X10_RECEIVER_FOUND"
    EVENT_SCAN_DEVICE_POPCORN_HOUR_FOUND = "SCAN_DEVICE_POPCORN_HOUR_FOUND"
    EVENT_SCAN_DEVICE_LIFX_FOUND = "SCAN_DEVICE_LIFX_FOUND"
    EVENT_SCAN_DEVICE_BROADLINK_FOUND = "SCAN_DEVICE_BROADLINK_FOUND"
    EVENT_SCAN_DEVICE_INSTEON_RECEIVER_FOUND = "SCAN_DEVICE_INSTEON_RECEIVER_FOUND"
    
    EVENT_PAIR_DEVICE_ABORT = "PAIR_DEVICE_ABORT"
    EVENT_PAIR_DEVICE_USER_ACTION_REQUIRED = "PAIR_DEVICE_USER_ACTION_REQUIRED"
    EVENT_PAIR_DEVICE_ERROR_AUTHENTICATION_FAIL = "PAIR_DEVICE_ERROR_AUTHENTICATION_FAIL"
    EVENT_PAIR_DEVICE_ERROR_INVALID_PARAMETER = "PAIR_DEVICE_ERROR_INVALID_PARAMETER"
    
    
    EVENT_UNPAIR_DEVICE = "UNPAIR_DEVICE"
    EVENT_UNPAIR_DEVICE_ZWAVE_USER_ACTION_REQUIRED = "UNPAIR_DEVICE_USER_ACTION_REQUIRED"
    EVENT_UNPAIR_DEVICE_ERROR_INVALID_PARAMETER = "UNPAIR_DEVICE_ERROR_INVALID_PARAMETER"
    EVENT_UNPAIR_DEVICE_ERROR_UNKNOWN = "UNPAIR_DEVICE_ERROR_UNKNOWN"
    EVENT_UNPAIR_DEVICE_ABORT = "UNPAIR_DEVICE_ABORT"

    '''
    Z-Wave Specific
    '''
    EVENT_ZWAVE_ADD_SECURE_NODE_FAILED = "ZWAVE_ADD_SECURE_NODE_FAILED"
    EVENT_ZWAVE_NETWORK_ADD_USER_ACTION_REQUIRED = "ZWAVE_NETWORK_ADD_USER_ACTION_REQUIRED"
    EVENT_ZWAVE_NETWORK_REMOVE_USER_ACTION_REQUIRED = "ZWAVE_NETWORK_REMOVE_USER_ACTION_REQUIRED"
    EVENT_ZWAVE_NETWORK_LEARN_USER_ACTION_REQUIRED = "ZWAVE_NETWORK_LEARN_USER_ACTION_REQUIRED"
    EVENT_ZWAVE_NETWORK_STATUS = "ZWAVE_NETWORK_STATUS" # Paired to device successfully
    EVENT_ZWAVE_NETWORK_REMOVE_FAILED_NODE = "ZWAVE_NETWORK_REMOVE_FAILED_NODE"
    EVENT_ZWAVE_NODE_STATUS = "ZWAVE_NODE_STATUS" # Found a device and before pairing to it
    EVENT_ZWAVE_NODE_INFO_UPDATE = "ZWAVE_NODE_INFO_UPDATE"
    EVENT_ZWAVE_TRANSMIT_STATUS = "ZWAVE_TRANSMIT_STATUS"
    EVENT_ZWAVE_BASIC_REPORT = "ZWAVE_BASIC_REPORT"
    EVENT_ZWAVE_GENERIC_REPORT = "ZWAVE_GENERIC_REPORT"
    EVENT_ZWAVE_METER_CAPABILITIES_REPORT = "ZWAVE_METER_CAPABILITIES_REPORT"
    EVENT_ZWAVE_METER_GET_REPORT = "ZWAVE_METER_GET_REPORT"
    EVENT_ZWAVE_LOCK_OPERATION_REPORT = "ZWAVE_LOCK_OPERATION_REPORT"
    EVENT_ZWAVE_BATTERY_REPORT = "ZWAVE_BATTERY_REPORT"
    EVENT_ZWAVE_ALARM_REPORT = "ZWAVE_ALARM_REPORT"
    EVENT_ZWAVE_ALARM_SUPPORTED_EVENT_REPORT = "ZWAVE_ALARM_SUPPORTED_EVENT_REPORT"
    EVENT_ZWAVE_SENSOR_MULTILEVEL_REPORT = "ZWAVE_SENSOR_MULTILEVEL_REPORT"
    EVENT_ZWAVE_BINARY_REPORT = "ZWAVE_BINARY_REPORT"
    EVENT_ZWAVE_SENSOR_MULTILEVEL_SUPPORTED_REPORT = "ZWAVE_SENSOR_MULTILEVEL_SUPPORTED_REPORT"
    EVENT_ZWAVE_SENSOR_MULTILEVEL_UNIT_REPORT = "ZWAVE_SENSOR_MULTILEVEL_UNIT_REPORT"
    EVENT_ZWAVE_CONFIGURATION_REPORT = "ZWAVE_CONFIGURATION_REPORT"
    EVENT_ZWAVE_USER_CODE_SUPPORT_REPORT = "ZWAVE_USER_CODE_SUPPORT_REPORT"
    EVENT_ZWAVE_USER_CODE_GET_REPORT = "ZWAVE_USER_CODE_GET_REPORT"
    EVENT_ZWAVE_GROUP_SUPPORTED_REPORT = "ZWAVE_GROUP_SUPPORTED_REPORT"
    EVENT_ZWAVE_GROUP_ACTIVE_REPORT = "ZWAVE_GROUP_ACTIVE_REPORT"
    EVENT_ZWAVE_GROUP_REPORT = "ZWAVE_GROUP_REPORT"
    EVENT_ZWAVE_SWITCH_MULTILEVEL_START_CHANGE = "ZWAVE_SWITCH_MULTILEVEL_START_CHANGE"
    EVENT_ZWAVE_SWITCH_MULTILEVEL_STOP_CHANGE = "ZWAVE_SWITCH_MULTILEVEL_STOP_CHANGE"
    EVENT_ZWAVE_SWITCH_MULTILEVEL_SUPPORTED_REPORT = "ZWAVE_SWITCH_MULTILEVEL_SUPPORTED_REPORT"
    EVENT_ZWAVE_MULTILEVEL_SENSOR_SUPPORTED_REPORT = "ZWAVE_MULTILEVEL_SENSOR_SUPPORTED_REPORT"
    EVENT_ZWAVE_MULTILEVEL_SENSOR_UNIT_REPORT = "ZWAVE_MULTILEVEL_SENSOR_UNIT_REPORT"
    EVENT_ZWAVE_WAKEUP_CAPABILITIES_REPORT = "ZWAVE_WAKEUP_CAPABILITIES_REPORT"
    EVENT_ZWAVE_THERMOSTAT_FAN_MODE_SUPPORTED_REPORT_RESPONSE = "ZWAVE_THERMOSTAT_FAN_MODE_SUPPORTED_REPORT_RESPONSE"
    EVENT_ZWAVE_THERMOSTAT_FAN_MODE_REPORT = "ZWAVE_THERMOSTAT_FAN_MODE_REPORT"
    EVENT_ZWAVE_THERMOSTAT_FAN_STATE_REPORT = "ZWAVE_THERMOSTAT_FAN_STATE_REPORT"
    EVENT_ZWAVE_THERMOSTAT_MODE_REPORT = "ZWAVE_THERMOSTAT_MODE_REPORT"
    EVENT_ZWAVE_THERMOSTAT_MODE_SUPPORTED_REPORT_RESPONSE = "ZWAVE_THERMOSTAT_MODE_SUPPORTED_REPORT_RESPONSE"
    EVENT_ZWAVE_THERMOSTAT_OPERATING_STATE_REPORT = "ZWAVE_THERMOSTAT_OPERATING_STATE_REPORT"
    EVENT_ZWAVE_THERMOSTAT_SETBACK_REPORT = "ZWAVE_THERMOSTAT_SETBACK_REPORT"
    EVENT_ZWAVE_THERMOSTAT_SETPOINT_REPORT = "ZWAVE_THERMOSTAT_SETPOINT_REPORT"
    EVENT_ZWAVE_THERMOSTAT_SETPOINT_SUPPORTED_REPORT_RESPONSE = "ZWAVE_THERMOSTAT_SETPOINT_SUPPORTED_REPORT_RESPONSE"
    EVENT_ZWAVE_BINARY_SENSOR_REPORT = "ZWAVE_BINARY_SENSOR_REPORT"
    EVENT_ZWAVE_NEIGHBOR_UPDATE_STATUS = "ZWAVE_NEIGHBOR_UPDATE_STATUS"
    EVENT_ZWAVE_ALARM_SUPPORTED_REPORT = "ZWAVE_ALARM_SUPPORTED_REPORT"
    EVENT_ZWAVE_APPLICATION_COMMAND_HANDLER = "ZWAVE_APPLICATION_COMMAND_HANDLER"
    EVENT_ZWAVE_NODE_INFO_RECEIVE = "ZWAVE_NODE_INFO_RECEIVE" # Received node information (pairing)
    EVENT_ZWAVE_ADD_SECURE_NODE_FAILED = "ZWAVE_ADD_SECURE_NODE_FAILED"  # Fail to get secure device information successfully, after paired
    EVENT_ZWAVE_ADD_SECURE_NODE_SUCCESS = "ZWAVE_ADD_SECURE_NODE_SUCCESS" # Get secure device information successfully, after paired
    EVENT_ZWAVE_NONSECURE_NODE_INCLUSION = "ZWAVE_NONSECURE_NODE_INCLUSION" # Get non-secure device information successfully, after paired
    EVENT_ZWAVE_UNKNOWN = "ZWAVE_UNKNOWN"

    '''
    X-10 Specific
    '''
    EVENT_X10_SCANNING_EVENT = "X10_SCANNING_EVENT"
    EVENT_X10_MOTION_SENSOR_EVENT = "X10_MOTION_SENSOR_EVENT"
    EVENT_X10_MOTION_OR_DOOR_WINDOW_SENSOR_EVENT = "X10_MOTION_OR_DOOR_WINDOW_SENSOR_EVENT"
    EVENT_X10_DOOR_WINDOW_SENSOR_EVENT = "X10_DOOR_WINDOW_SENSOR_EVENT"
    EVENT_X10_KEYCHAIN_REMOTE_EVENT = "X10_KEYCHAIN_REMOTE_EVENT"
    EVENT_X10_PANIC_BUTTON_EVENT = "X10_PANIC_BUTTON_EVENT"
    EVENT_X10_ON_HORN_EVENT = "X10_ON_HORN_EVENT"
    EVENT_X10_APPLIANCE_EVENT = "X10_APPLIANCE_EVENT"
    EVENT_X10_UNKNOWN_MODEL_EVENT = "X10_UNKNOWN_MODEL_EVENT"

    '''
    Dust Specific
    '''
    EVENT_DUST_REPLY = "DUST_REPLY"
    EVENT_DUST_STATUS = "DUST_STATUS"
    EVENT_DUST_NOTIF_EVENT_MOTE_RESET = "DUST_NOTIF_EVENT_MOTE_RESET"
    EVENT_DUST_NOTIF_EVENT_NETWORK_RESET = "DUST_NOTIF_EVENT_NETWORK_RESET"
    EVENT_DUST_NOTIF_EVENT_COMMAND_FINISH = "DUST_NOTIF_EVENT_COMMAND_FINISH"
    EVENT_DUST_NOTIF_EVENT_MOTE_JOIN = "DUST_NOTIF_EVENT_MOTE_JOIN"
    EVENT_DUST_NOTIF_EVENT_MOTE_OPERATIONAL = "DUST_NOTIF_EVENT_MOTE_OPERATIONAL"
    EVENT_DUST_NOTIF_EVENT_MOTE_LOST = "DUST_NOTIF_EVENT_MOTE_LOST"
    EVENT_DUST_NOTIF_EVENT_NETWORK_TIME = "DUST_NOTIF_EVENT_NETWORK_TIME"
    EVENT_DUST_NOTIF_EVENT_PING_RESPONSE = "DUST_NOTIF_EVENT_PING_RESPONSE"
    EVENT_DUST_NOTIF_EVENT_PATH_CREATE = "DUST_NOTIF_EVENT_PATH_CREATE"
    EVENT_DUST_NOTIF_EVENT_PATH_DELETE = "DUST_NOTIF_EVENT_PATH_DELETE"
    EVENT_DUST_NOTIF_EVENT_PACKET_SENT = "DUST_NOTIF_EVENT_PACKET_SENT"
    EVENT_DUST_NOTIF_EVENT_MOTE_CREATE = "DUST_NOTIF_EVENT_MOTE_CREATE"
    EVENT_DUST_NOTIF_EVENT_MOTE_DELETE = "DUST_NOTIF_EVENT_MOTE_DELETE"
    EVENT_DUST_NOTIF_LOG = "DUST_NOTIF_LOG"
    EVENT_DUST_NOTIF_DATA = "DUST_NOTIF_DATA"
    EVENT_DUST_NOTIF_IP_DATA = "DUST_NOTIF_IP_DATA"
    EVENT_DUST_NOTIF_HEALTH_REPORT = "DUST_NOTIF_HEALTH_REPORT"

    '''
    Insteon Specific
    '''
    EVENT_INSTEON_DEVICE_STATUS = "INSTEON_DEVICE_STATUS"
    EVENT_INSTEON_LINKING_COMPLETE = "INSTEON_LINKING_COMPLETE"
    EVENT_INSTEON_DELETE_LINK_COMPLETE = "INSTEON_DELETE_LINK_COMPLETE"
    EVENT_INSTEON_LINKING_STARTED = "INSTEON_LINKING_STARTED"
    EVENT_INSTEON_LINKING_STOPPED = "INSTEON_LINKING_STOPPED"
    EVENT_INSTEON_DELETE_LINK_STARTED = "INSTEON_DELETE_LINK_STARTED"
    EVENT_INSTEON_LINKING_TIMEOUT = "INSTEON_LINKING_TIMEOUT"
    EVENT_INSTEON_DEVICE_SCAN_COMPLETE = "INSTEON_DEVICE_SCAN_COMPLETE"
    EVENT_INSTEON_HUB_ACCESS_TIMEOUT = "INSTEON_HUB_ACCESS_TIMEOUT"
    EVENT_INSTEON_DATA_RESPONSE = "INSTEON_HUB_DATA_RESPONSE"
    
    '''
    ZigBee Specific
    '''
    EVENT_ZIGBEE_DEVICE_UPDATE_ATTRIBUTE = "ZIGBEE_DEVICE_UPDATE_ATTRIBUTE"
    EVENT_ZIGBEE_DEVICE_READ_ATTRIBUTE_FAILED = "ZIGBEE_DEVICE_READ_ATTRIBUTE_FAILED"
    EVENT_ZIGBEE_DEVICE_UPDATE_ATTRIBUTE_FAILED = "ZIGBEE_DEVICE_UPDATE_ATTRIBUTE_FAILED"
    EVENT_ZIGBEE_PERMIT_JOIN_TIME = "ZIGBEE_PERMIT_JOIN_TIME"
    EVENT_ZIGBEE_DEVICE_ADD = "ZIGBEE_DEVICE_ADD"
    
    '''
    FTDI Specific
    '''
    EVENT_FTDI_READ = "FTDI_READ"

    '''
    AFFINEX's FTDI Specific
    '''
    EVENT_AFFINEX_FTDI_DEV_KIT_INPUT_PRESS = "AFFINEX_FTDI_DEV_KIT_INPUT_PRESS"
    EVENT_AFFINEX_FTDI_DEV_KIT_TURN_ON_LED = "AFFINEX_FTDI_DEV_KIT_TURN_ON_LED"

    EVENT_HDL_MIRACLE = "HDL_MIRACLE"

    '''
    UPNP Service Specific
    '''
    EVENT_UPNP_SERVICE_PLAYBACK_STARTED = "UPNP_SERVICE_PLAYBACK_STARTED"
    EVENT_UPNP_SERVICE_PLAYBACK_PLAYING = "UPNP_SERVICE_PLAYBACK_PLAYING"
    EVENT_UPNP_SERVICE_PLAYBACK_PAUSED = "UPNP_SERVICE_PLAYBACK_PAUSED"
    EVENT_UPNP_SERVICE_PLAYBACK_STOPPED = "UPNP_SERVICE_PLAYBACK_STOPPED"
    EVENT_UPNP_SERVICE_PLAYBACK_VOLUME_CHANGED = "UPNP_SERVICE_PLAYBACK_VOLUME_CHANGED"
    EVENT_UPNP_SERVICE_PLAYBACK_MUTE_STATE_CHANGED = "UPNP_SERVICE_PLAYBACK_MUTE_STATE_CHANGED"
    EVENT_UPNP_SERVICE_PLAYBACK_INFO_UPDATED = "UPNP_SERVICE_PLAYBACK_INFO_UPDATED"

    '''
    SYB Player Specific
    '''
    EVENT_SYB_PLAYER_INFO = "SYB_PLAYER_INFO"

    '''
    WeMo Service Specific
    '''
    EVENT_WEMO_SENSOR_MOTION_DETECTED = "WEMO_SENSOR_MOTION_DETECTED"

    '''
    Speaker Controller Specific
    '''
    # For Automation Only
    #EVENT_SPEAKER_CONTROLLER_PLAYBACK_STARTED = "SPEAKER_CONTROLLER_PLAYBACK_STARTED"
    EVENT_SPEAKER_CONTROLLER_PLAYBACK_STATE_CHANGED = "SPEAKER_CONTROLLER_PLAYBACK_STATE_CHANGED"
    EVENT_SPEAKER_CONTROLLER_PLAYBACK_VOLUME_CHANGED = "SPEAKER_CONTROLLER_PLAYBACK_VOLUME_CHANGED"
    EVENT_SPEAKER_CONTROLLER_PLAYBACK_MUTE_STATE_CHANGED = "SPEAKER_CONTROLLER_PLAYBACK_MUTE_STATE_CHANGED"
  
    EVENT_SPEAKER_CONTROLLER_DEVICE_ENABLED = "SPEAKER_CONTROLLER_DEVICE_ENABLED"
    EVENT_SPEAKER_CONTROLLER_PLAYBACK_INFO_UPDATED = "SPEAKER_CONTROLLER_PLAYBACK_INFO_UPDATED"
    
    EVENT_SPEAKER_CONTROLLER_INIT_STATUS = "SPEAKER_CONTROLLER_INIT_STATUS"
    EVENT_SPEAKER_CONTROLLER_CONNECTING = "SPEAKER_CONTROLLER_CONNECTING"
    EVENT_SPEAKER_CONTROLLER_CONNECTED = "SPEAKER_CONTROLLER_CONNECTED"
    EVENT_SPEAKER_CONTROLLER_DISCONNECTING = "SPEAKER_CONTROLLER_DISCONNECTING"
    EVENT_SPEAKER_CONTROLLER_DISCONNECTED = "SPEAKER_CONTROLLER_DISCONNECTED"

    '''
    Sensor Controller Specific
    '''
    EVENT_SENSOR_CONTROLLER_DEVICE_ENABLED = "SENSOR_CONTROLLER_DEVICE_ENABLED"
    EVENT_SENSOR_CONTROLLER_MOTION = "SENSOR_CONTROLLER_MOTION"
    EVENT_SENSOR_CONTROLLER_LIGHT = "SENSOR_CONTROLLER_LIGHT"
    EVENT_SENSOR_CONTROLLER_DOOR_WINDOW = "SENSOR_CONTROLLER_DOOR_WINDOW"
    EVENT_SENSOR_CONTROLLER_SENSOR = "SENSOR_CONTROLLER_SENSOR"
    EVENT_SENSOR_CONTROLLER_ALARM = "SENSOR_CONTROLLER_ALARM"
    EVENT_SENSOR_CONTROLLER_SMOKE_ALARM = "SENSOR_CONTROLLER_SMOKE_ALARM"
    EVENT_SENSOR_CONTROLLER_CO_ALARM = "SENSOR_CONTROLLER_CO_ALARM"
    EVENT_SENSOR_CONTROLLER_LEAK  = "SENSOR_CONTROLLER_LEAK"
    
    '''
    Switch Controller Specific
    '''
    EVENT_SWITCH_CONTROLLER_DEVICE_ENABLED = "SWITCH_CONTROLLER_DEVICE_ENABLED"
    EVENT_SWITCH_CONTROLLER_STATE_CHANGED = "SWITCH_CONTROLLER_STATE_CHANGED"
    
    '''
    Switch No Status Controller Specific
    '''
    EVENT_SWITCH_NO_STATUS_CONTROLLER_DEVICE_ENABLED = "SWITCH_NO_STATUS_CONTROLLER_DEVICE_ENABLED"

    '''
    Dimmer Controller Specific
    '''
    EVENT_DIMMER_CONTROLLER_DEVICE_ENABLED = "DIMMER_CONTROLLER_DEVICE_ENABLED"
    EVENT_DIMMER_CONTROLLER_STATE_CHANGED = "DIMMER_CONTROLLER_STATE_CHANGED" # On/Off + Dim level
    EVENT_DIMMER_CONTROLLER_STATUS_CHANGED = "DIMMER_CONTROLLER_STATUS_CHANGED" # On/Off Only
    EVENT_DIMMER_CONTROLLER_DIM_LEVEL_CHANGED = "DIMMER_CONTROLLER_DIM_LEVEL_CHANGED" # Dim level only

    '''
    Dimmer Step Controller Specific
    '''
    EVENT_DIMMER_STEPPER_CONTROLLER_DEVICE_ENABLED = "DIMMER_STEPPER_CONTROLLER_DEVICE_ENABLED"
    EVENT_DIMMER_STEPPER_CONTROLLER_STATE_CHANGED = "DIMMER_STEPPER_CONTROLLER_STATE_CHANGED"

    '''
    Horn Controller Specific
    '''
    EVENT_HORN_CONTROLLER_DEVICE_ENABLED = "HORN_CONTROLLER_DEVICE_ENABLED"
    EVENT_HORN_CONTROLLER_STATE_CHANGED = "HORN_CONTROLLER_STATE_CHANGED"

    '''
    Power Strip Controller Specific
    '''
    EVENT_POWER_STRIP_CONTROLLER_DEVICE_ENABLED = "POWER_STRIP_CONTROLLER_DEVICE_ENABLED"
    EVENT_POWER_STRIP_CONTROLLER_STATE_CHANGED = "POWER_STRIP_CONTROLLER_STATE_CHANGED"

    '''
    Hue Controller Specific
    '''
    EVENT_HUE_CONTROLLER_DEVICE_ENABLED = "HUE_CONTROLLER_DEVICE_ENABLED"
    EVENT_HUE_CONTROLLER_STATE_CHANGED = "HUE_CONTROLLER_STATE_CHANGED"

    '''
    Door Lock Controller Specific
    '''
    EVENT_DOOR_LOCK_CONTROLLER_DEVICE_ENABLED = "DOOR_LOCK_CONTROLLER_DEVICE_ENABLED"
    EVENT_DOOR_LOCK_CONTROLLER_STATE_CHANGED = "DOOR_LOCK_CONTROLLER_STATE_CHANGED"
    EVENT_DOOR_LOCK_CONTROLLER_BATTERY_LOW = "DOOR_LOCK_CONTROLLER_BATTERY_LOW"

    '''
    IP Camera Controller Specific
    '''
    EVENT_IP_CAMERA_CONTROLLER_DEVICE_ENABLED = "IP_CAMERA_CONTROLLER_DEVICE_ENABLED"
    
    '''
    Traker Controller Specific
    '''
    EVENT_TRACKER_CONTROLLER_DEVICE_ENABLED = "TRACKER_CONTROLLER_DEVICE_ENABLED"
    
    '''
    Traker Controller Specific
    '''
    EVENT_VIRTUAL_ACTIVITY_CONTROLLER_DEVICE_ENABLED = "VIRTUAL_ACTIVITY_CONTROLLER_DEVICE_ENABLED"
    
    '''
    Weather Service Specific
    '''
    EVENT_WEATHER_SERVICE_WEATHER_STATUS_CHANGED = "WEATHER_STATUS_CHANGED"
    EVENT_WEATHER_SERVICE_WIND_DIRECTION_CHANGED = "WEATHER_WIND_DIRECTION_CHANGED"
    EVENT_WEATHER_SERVICE_DAYLIGHT_CHANGED = "WEATHER_SERVICE_DAYLIGHT_CHANGED"
    EVENT_WEATHER_TEMPERATURE_UNIT_CHANGED = "WEATHER_TEMPERATURE_UNIT_CHANGED"
    EVENT_WEATHER_SERVICE_TEMPERATURE_CHANGED = "WEATHER_TEMPERATURE_CHANGED"
    EVENT_WEATHER_SERVICE_HUMIDITY_CHANGED = "WEATHER_HUMIDITY_CHANGED"
    EVENT_WEATHER_SERVICE_WIND_SPEED_CHANGED = "WEATHER_WIND_SPEED_CHANGED"
    EVENT_WEATHER_SERVICE_FORECAST_WEATHER_CHANGED = "WEATHER_FORECAST_WEATHER_CHANGED"
    
    '''
    IMAP Service Specific
    '''
    # EVENT_IMAP_SERVICE_RECEIVED_INCOMING_MESSAGE = "IMAP_RECEIVED_INCOMING_MESSAGE"
    
    '''
    SMTP Service Specific
    '''
    EVENT_SMTP_SERVICE_SENDER_LIST_CHANGED = "SMTP_SERVICE_SENDER_LIST_CHANGED"
    EVENT_SMTP_SERVICE_RECIPIENT_LIST_CHANGED = "SMTP_SERVICE_RECIPIENT_LIST_CHANGED"
    EVENT_SMTP_SERVICE_STATUS_CHANGED = "SMTP_SERVICE_STATUS_CHANGED"
    
    '''
    Twitter Service Specific
    '''
    EVENT_TWITTER_SERVICE_RECEIVED_MESSAGE = "TWITTER_SERVICE_RECEIVED_MESSAGE"
    EVENT_TWITTER_SERVICE_SENDER_LIST_CHANGED = "TWITTER_SERVICE_SENDER_LIST_CHANGED"
    EVENT_TWITTER_SERVICE_RECIPIENT_LIST_CHANGED  = "TWITTER_SERVICE_RECIPIENT_LIST_CHANGED"
    EVENT_TWITTER_SERVICE_STATUS_CHANGED = "TWITTER_SERVICE_STATUS_CHANGED"
    
    '''
    Bluetooth
    '''
    EVENT_BLUETOOTH = "BLUETOOTH"

    '''
    Bluetooth Low Energy
    '''
    EVENT_BLE_CONNECTED = "BLE_CONNECTED"
    EVENT_BLE_DISCONNECTED = "BLE_DISCONNECTED"
    EVENT_BLE_ALIVE = "BLE_ALIVE"
    EVENT_BLE_DEAD = "BLE_DEAD"
    EVENT_BLE_SERVICES = "BLE_SERVICES"
    EVENT_BLE_CHARACTERISTICS = "BLE_CHARACTERISTICS"
    EVENT_BLE_READ_TYPE_RESPONSE = "BLE_READ_TYPE_RESPONSE"
    EVENT_BLE_READ_HANDLE_RESPONSE = "BLE_READ_HANDLE_RESPONSE"
    EVENT_BLE_WRITE_REQUEST_RESPONSE = "BLE_WRITE_REQUEST_RESPONSE"
    EVENT_BLE_NOTIFICATION = "BLE_NOTIFICATION"
    EVENT_BLE_DEVICE_TYPE = "BLE_DEVICE_TYPE" # For module only.

    '''
    Tiny Finder
    '''
    EVENT_TINY_FINDER_BATTERY = "TINY_FINDER_BATTERY"
    EVENT_TINY_FINDER_LINK_LOSS = "TINY_FINDER_LINK_LOSS"
    
    '''
    Media Player Specific
    '''
    EVENT_MEDIA_PLAYER_CONTROLLER_DEVICE_ENABLED = "MEDIA_PLAYER_CONTROLLER_DEVICE_ENABLED"
    EVENT_MEDIA_PLAYER_PLAYBACK_STATE_CHANGED = "MEDIA_PLAYER_PLAYBACK_STATE_CHANGED"
    EVENT_MEDIA_PLAYER_MUTE_STATE_CHANGED = "MEDIA_PLAYER_MUTE_STATE_CHANGED"
    EVENT_MEDIA_PLAYER_PLAYBACK_STATUS_RECEIVED = "MEDIA_PLAYER_PLAYBACK_STATUS_RECEIVED"
    
    '''
    Virtual Remote Controller Specific
    '''
    EVENT_VIRTUAL_REMOTE_CONTROL_DEVICE_ENABLED = "VIRTUAL_REMOTE_CONTROL_DEVICE_ENABLED"
    EVENT_VIRTUAL_REMOTE_CONTROL_KEY_CHANGED = "VIRTUAL_REMOTE_CONTROL_KEY_CHANGED"
    EVENT_VIRTUAL_REMOTE_CONTROL_INFO_CHANGED = "VIRTUAL_REMOTE_CONTROL_INFO_CHANGED"
    EVENT_VIRTUAL_REMOTE_CONTROL_RECORD_KEY_START = "VIRTUAL_REMOTE_CONTROL_RECORD_KEY_START"
    EVENT_VIRTUAL_REMOTE_CONTROL_RECORD_KEY_ERROR = "VIRTUAL_REMOTE_CONTROL_RECORD_KEY_ERROR"
    EVENT_VIRTUAL_REMOTE_CONTROL_RECORD_KEY_FINISH = "VIRTUAL_REMOTE_CONTROL_RECORD_KEY_FINISH"
    
    '''
    Popcorn Hour Specific
    '''
    EVENT_POPCORN_HOUR_PLAYBACK_START = "POPCORN_HOUR_PLAYBACK_START"
    EVENT_POPCORN_HOUR_PLAYBACK_END = "POPCORN_HOUR_PLAYBACK_END"
    EVENT_POPCORN_HOUR_PLAYBACK_TERMINATE = "POPCORN_HOUR_PLAYBACK_TERMINATE"
    EVENT_POPCORN_HOUR_PLAYBACK_STATUS = "POPCORN_HOUR_PLAYBACK_STATUS"
    EVENT_POPCORN_HOUR_SLIDESHOW_START = "POPCORN_HOUR_SLIDESHOW_START"
    EVENT_POPCORN_HOUR_SLIDESHOW_END = "POPCORN_HOUR_SLIDESHOW_END"
    EVENT_POPCORN_HOUR_SLIDESHOW_TERMINATE = "POPCORN_HOUR_SLIDESHOW_TERMINATE"
    EVENT_POPCORN_HOUR_SLIDESHOW_NEXT = "POPCORN_HOUR_SLIDESHOW_NEXT"
    
    '''
    Logitech Harmony Specific
    '''
    EVENT_LOGITECH_HARMONY_ACTIVITY_STARTED = "LOGITECH_HARMONY_ACTIVITY_STARTED"
    EVENT_LOGITECH_HARMONY_ACTIVITY_START_TIMEOUT = "LOGITECH_HARMONY_ACTIVITY_START_TIMEOUT"
    
    '''
    Thermostat Specific
    '''
    EVENT_THERMOSTAT_CONTROLLER_DEVICE_ENABLED = "THERMOSTAT_CONTROLLER_DEVICE_ENABLED"
    
    '''
    Z-Wave Advance Controller Specific
    '''
    EVENT_ZWAVE_ADV_CONTROLLER_BASIC_SET_SEND = "ZWAVE_ADV_CONTROLLER_BASIC_SET_SEND"
    EVENT_ZWAVE_ADV_CONTROLLER_ALARM_REPORT = "ZWAVE_ADV_CONTROLLER_ALARM_REPORT"
    EVENT_ZWAVE_ADV_CONTROLLER_SENSOR_ALARM_REPORT = "ZWAVE_ADV_CONTROLLER_SENSOR_ALARM_REPORT"
    
    '''
    Unsupported Device Specific
    '''
    EVENT_UNSUPPORTED_CONTROLLER_DEVICE_ENABLED = "UNSUPPORTED_CONTROLLER_DEVICE_ENABLED"

    '''
    Shared Methods
    '''
    EVENT_SHARED_METHOD_ADDED = "SHARED_METHOD_ADDED" # When app added a shared method.
    EVENT_SHARED_METHOD_UPDATED = "SHARED_METHOD_UPDATED" # When app overwrote a previously added shared method.
    EVENT_SHARED_METHOD_DELETED = "SHARED_METHOD_DELETED" # When app removed a previously added shared method.
    EVENT_SHARED_METHOD_ACTIVATED = "SHARED_METHOD_ACTIVATED" # When a shared method changed its status from inactive to active. Updated/Added event will be broadcasted as well.
    EVENT_SHARED_METHOD_DEACTIVATED = "SHARED_METHOD_DEACTIVATED" # When a shared method changed its status from active to inactive. Updated/Added event will be broadcasted as well.
    
    EVENT_SHARED_METHOD_GROUP_ADDED = "SHARED_METHOD_GROUP_ADDED" # When app added a shared method group.
    EVENT_SHARED_METHOD_GROUP_DELETED = "SHARED_METHOD_GROUP_DELETED" # When app removed a previously added shared method group.
    EVENT_SHARED_METHOD_GROUP_UPDATED = "SHARED_METHOD_GROUP_UPDATED" # When app overwrote a previously added shared method group.
    

    
    '''
    Location Manager
    '''
    EVENT_LOCATION_ADDED = "LOCATION_ADDED"
    EVENT_LOCATION_DELETED = "LOCATION_DELETED"
    EVENT_LOCATION_UPDATED = "LOCATION_UPDATED"
    EVENT_LOCATION_LIST_CHANGED = "LOCATION_LIST_CHANGED"

